### ISSUE TITLE
Generation of simulator with DoubleScalar READ_WRITE attribute

### ISSUE THREAD

**Issue by dalifard** [tango-controls/SimulatorDS#10] opened 2018-10-26 08:44 UTC
Hello,

I tried to generate a simulator for my PowerSupply DS. 

I noticed that the 4 DoubleScalar READ_WRITE attributes are generated as READ attributes (not READ_WRITE). See the snapshot below with the original DS to the left and the simulated one to the right and the PCK generated file.

All the process has been done on the same Debian 9/Tango 9 server with fandango (14.3.0) and SimulatorDS 4.2

Have you got any idea why this occurs? 

![ATKPanels](https://owncloud.lal.in2p3.fr/index.php/s/eoLf45MYE0LbXL1/download)

**Comment by PhilLAL** [comment] 2018-10-26 15:14
Hi, 
I also noticed that TangoTest simulated DS ATKPanel has some differences with original TangoTest:
- following attributes ar in READ mode (in Simulated DS) instead of READ_WRITE (in original one):

  * double_scalar
  * float_scalar
  * long64_scalar 
  * long_scalar
  * short_scalar
  * string_scalar
  * ulong64_scalar
  * ulong_scalar
  * ushort_scalar

- several attributes are in READ_WRITE instead of READ_WITH_WRITE (perhaps is it because this mode is deprecated?):

  * double_scalar_rww
  * long_scalar_rww
  * short_scalar_rww

**Comment by PhilLAL** [comment] 2018-11-07 14:15
Up to check if anyone has some trick to avoid this. 
Perhaps we did not understood well the behaviour of SimulatorDS.

**Comment by sergirubio** [comment] 2018-11-08 09:20
Working on that ...

**Comment by sergirubio** [comment] 2018-11-08 09:59
The problem seems to come from PyTango, when I execute DeviceProxy('sys/tg_test/1').get_attribute_config('double_scalar').writable it returns WT_UNKNOWN instead of the expected READ_WRITE that appears in Jive

I'm going to push a patch to consider scalar UNKNOWN as READ_WRITE; but a patch in PyTango or a debugging of the issue will be needed.

**Comment by sergirubio** [comment] 2018-11-08 15:00
I didn't have time to finish the patch, but I have verified that big array attributes also give problems to SimulatorDS

Please, try to verify SimulatorDS on an smaller device and i'll try to publish a patch during the next week

**Comment by PhilLAL** [comment] 2018-11-15 16:19
We tried SimulatorDS on GenericPowerSupply as described upside (GenPoSup and GenPoSup_simu) which is smaller, but encounter the same behaviour. 
Could we give you more more data to help you helping us? :)

**Comment by PhilLAL** [comment] 2018-12-06 12:28
Hi Sergi, 
I precise that the 2d test with TangoTest has been made to check if we the behavior we got on GenericPowerSupply on another DS (TangoTest here).
Our use case is GenericPowerSupply, which contains much less attributes than TangoTest.

**Comment by sergirubio** [comment] 2018-12-10 16:58
.... uuuh, could you describe a bit better the user case? I want to understand what you actually need

**Comment by PhilLAL** [comment] 2018-12-10 17:54
When we use the SimulatorDS, we would like to set a value for CurrentSetPointPM attribute of SimulatorDS and then read this value by reading CurrentSetPointPM attribute of the same SimulatorDS.
This is why I need read and **write** access for attributes.

**Comment by sergirubio** [comment] 2018-12-14 12:52
Ok, in principle it should have been already solved with parsing of UNKNOWN attribute format; but anyway I'm going to add a couple of helper functions to simplify writing simulated attributes

**Comment by PhilLAL** [comment] 2018-12-14 16:07
Oh, Ok, I'll try then before making you doing more work. I just was not aware this has been solved. 
Sorry.

**Comment by PhilLAL** [comment] 2019-02-13 08:22
Hi @sergirubio 
you said to me this bug has finally been solved during kernel camp, but could you detail what package(s) should we updated to fix things?
Thank you. :)

**Comment by PhilLAL** [comment] 2019-02-20 08:23
Hi @sergirubio I can check it works if you let me know of to test this new version.
Thx

**Comment by PhilLAL** [comment] 2019-03-05 15:00
Up to check if anyone has some trick to avoid this. 
Perhaps we did not understood well the behaviour of SimulatorDS.

**Comment by sergirubio** [comment] 2019-03-07 10:33
Hi PhiLAL,

The problem is that there's not yet a PyTango package including the fix, we should wait until it is released (expected in June)

Of course, you can compile PyTango+Tango using the latest sources from github, but I don't think this is production-ready yet.

Until then ... I would continue using my patch that considers all WT_UNKOWN as READ/WRITE ... it didn't worked for you?

Sergi

**Comment by PhilLAL** [comment] 2019-03-08 15:45
Hi @sergirubio 
I wanted to test the new correction but no problem.
Thank you again :)

**Comment by sergirubio** [comment] 2019-04-16 08:31
Hi PhilLAL

There's actually a new PyTango 9.3 version that solves this issue; and simulatords has a patch to bypass it on earlier versions. 

I close the issue

Sergi

**Closed as completed by sergirubio** 2019-04-16 08:31 UTC
